version: "3.9"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  
  webapp:
    build:
      dockerfile: ./docker/Dockerfile.api
      context: ./
    image: webapp
    ports:
      - "8000:8000"
    env_file: ./.env
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - "./:/code"