version: "3.9"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}